sudo: false
language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
cache: npm
script: npm run lint && npm test
jobs:
  include:
    - name: e2e-test
      script: npm run e2e-test
      node_js: '10'
  allow_failures:
    - name: e2e-test
