sudo: false
language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
cache: npm
script:
  - npm run lint
  - npm run test
jobs:
  include:
    - name: test-e2e
      script: npm run test-e2e
      node_js: '10'
  allow_failures:
    - name: test-e2e
